ARG JDK_VERSION
FROM openjdk:${JDK_VERSION}

WORKDIR /app

ARG APP_MODULE_NAME
ENV APP_MODULE_NAME=$APP_MODULE_NAME

ARG APP_VERSION
ENV APP_VERSION=$APP_VERSION

COPY $APP_MODULE_NAME/target/$APP_MODULE_NAME-$APP_VERSION.jar /app

CMD java -jar /app/$APP_MODULE_NAME-$APP_VERSION.jar