server:
  port: 8082

app:
  webSecurityEnable: !!bool false

logging:
  level:
    root: INFO

spring:
  application:
    name: web-store
  output:
    ansi:
      enabled: always
  profiles:
    active: secrets, database-h2, oath2
