spring:
  datasource:
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 75MB