server:
  port: 8082

app:
  webSecurity:
    enabled: !!bool true
    login:
      viaGoogle: !!bool false
  rememberMe:
    time: !!int 8400
    key: !!str secretAndUnique
    cookieName: !!str rememberMe

logging:
  level:
    root: INFO

spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: secrets, database-h2, oath2
