spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_SECRET}
            clientSecret: ${GOOGLE_CLIENT_ID}
            scope:
              - email
              - profile