spring:
  h2:
    console:
      enabled: true
      path: !!str /h2
  datasource:
    url: ${h2.url}
    username: ${h2.username}
    password: ${h2.password}
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
