spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/db/demo;AUTO_SERVER=TRUE
    username: "sa"
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
